package devreux.TechnoMarket.entity;

public enum TipoMovimiento {
    ENTRADA, //INDICA QUE SE AGREGO PRODUCTOS NUEVOS AL INVENTARIO, POR COMPRA O REPOSICION
    SALIDA  //INDICA QUE SE SACARON PRODUCTOS DEL INVENTARIO POR COMPRA O RETIRO DE VENTA
}
