spring:
  application:
    name: LogIn

  # Configuración de la Base de Datos Oracle
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: ben002300
    driver-class-name: oracle.jdbc.OracleDriver

  # Configuración de JPA e Hibernate
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false # Esto hace que el SQL en consola se vea ordenado